### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by Pandan** [SamirL/pixijs-webpack-starter#1]
Hi,
I am trying to setup pixi 4 with webpack. 
Actually spent a couple of hours checking out different setups but still can't get it to work.
I had it running good with v3 but as soon I tried switching to v4 it broke. 
I am guessing it might be connected to the switch to es6 and the more modular approach. 

When I saw your starter project and that you where using v4.0.1 I got my hopes up. 
But I can't get it to run, - "Cannot read property 'autoDetectRenderer' of undefined"
It's actually similar to what I have encountered earlier and that the imports does not work correctly. 
Any ideas?

**Comment by SamirL** [comment]
Hi,

I will take a look and get back to you.

**Comment by SamirL** [comment]
Hi,

It seems there has been a pixi.js update, i will try to take care of it today and push an update.
Thank you for telling me.

**Comment by Pandan** [comment]
Great!
I looked around a bit but haven't found a solution yet.
Here is some information;
https://github.com/pixijs/pixi.js/issues/1854
But the different solutions in that thread are a bit old and probably only working for v.3 . None of them worked for me.

**Comment by mpinter** [comment]
+1, I seem to be stuck on the same problem

thanks for looking into it

**Comment by SamirL** [comment]
Fixed, cleaning up and pushing the update.

**Comment by SamirL** [comment]
@mpinter @Pandan The fix has been pushed. Let me know if it is working on your side please, thanks !

**Comment by SamirL** [comment]
Hi Jonas,

I will take a look in the coming hour and get back to you.

Cheers !

From: Jonas Törnqvist <notifications@github.com> <notifications@github.com>
Reply: SamirL/pixijs-webpack-starter
<reply@reply.github.com>
<reply@reply.github.com>
Date: 23 October 2016 at 13:08:15
To: SamirL/pixijs-webpack-starter
<pixijs-webpack-starter@noreply.github.com>
<pixijs-webpack-starter@noreply.github.com>
Subject:  [SamirL/pixijs-webpack-starter] Webpack (#1)

Hi,
I am trying to setup pixi 4 with webpack.
Actually spent a couple of hours checking out different setups but still
can't get it to work.
I had it running good with v3 but as soon I tried switching to v4 it broke.
I am guessing it might be connected to the switch to es6 and the more
modular approach.

When I saw your starter project and that you where using v4.0.1 I got my
hopes up.
But I can't get it to run, - "Cannot read property 'autoDetectRenderer' of
undefined"
It's actually similar to what I have encountered earlier and that the
imports does not work correctly.
Any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SamirL/pixijs-webpack-starter/issues/1>, or mute the
thread

**Comment by Pandan** [comment]
Sounds great!
I will try todo a test as soon as I can and get back to u!
Great work,

**Comment by SamirL** [comment]
Perfect thanks !

**Comment by Pandan** [comment]
Your solution worked! 
Here is some more info on the topic.
https://github.com/pixijs/pixi.js/issues/3204

**Comment by SamirL** [comment]
Awesome, thank you for the feedback and the additional info. I will keep track of their implementation and do the necessary changes when possible.
